// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using OCTVision.Frame.Debug;
using EasyPacking;

namespace EasyPacking_IOS
{
	public partial class MainPageController : UITableViewController
	{
		public MainPageController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			//Test
			Debugger.log_level = LogLevel.LL_ALL;
			TravelDataMng.instance.LoadFromXml ();
			TableView.Source = new MainPageSource ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}
	}
}
