// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace EasyPacking_IOS
{
	public partial class MainPageController : UITableViewController
	{
		public MainPageController (IntPtr handle) : base (handle)
		{
		}
	}
}
